### ISSUE TITLE
Deprecation message from ember-getowner-polyfill

### ISSUE THREAD

**Issue by shijistar** [sethwebster/ember-cli-new-version#32]
Is it possible to remove this deprecation message? I'm using Ember 2.10.0.

```
DEPRECATION: ember-getowner-polyfill is now a true polyfill. Use Ember.getOwner directly instead of importing from ember-getowner-polyfill [deprecation id: ember-getowner-polyfill.import]
        at logDeprecationStackTrace (http://s_insight2.udesk.cn/site/assets/vendor.js:27268:19)
        at HANDLERS.(anonymous function) (http://s_insight2.udesk.cn/site/assets/vendor.js:27378:7)
        at raiseOnDeprecation (http://s_insight2.udesk.cn/site/assets/vendor.js:27298:12)
        at HANDLERS.(anonymous function) (http://s_insight2.udesk.cn/site/assets/vendor.js:27378:7)
        at handleDeprecationWorkflow (http://s_insight2.udesk.cn/site/assets/vendor.js:80665:9)
        at HANDLERS.(anonymous function) (http://s_insight2.udesk.cn/site/assets/vendor.js:27378:7)
        at deprecationCollector (http://s_insight2.udesk.cn/site/assets/vendor.js:80690:5)
        at HANDLERS.(anonymous function) (http://s_insight2.udesk.cn/site/assets/vendor.js:27378:7)
        at invoke (http://s_insight2.udesk.cn/site/assets/vendor.js:27394:7)
```

**Comment by knownasilya** [comment]
I don't think that's coming from this addon, since it's only included in devDependencies, and wouldn't be installed on a consumer's machine. Try `npm ls ember-getowner-polyfill` in your app.
